export type CourtCode = {
  code: string;
  name: string;
};

export const COURT_CODES: CourtCode[] = [
  { code: "BB1B", name: "BIELSKO-BIAŁA" },
  { code: "BB1C", name: "CIESZYN" },
  { code: "BB1Z", name: "ŻYWIEC" },
  { code: "BI1B", name: "BIAŁYSTOK" },
  { code: "BI1P", name: "BIELSK PODLASKI" },
  { code: "BI1S", name: "SOKÓŁKA" },
  { code: "BI2P", name: "HAJNÓWKA" },
  { code: "BI3P", name: "SIEMIATYCZE" },
  { code: "BY1B", name: "BYDGOSZCZ" },
  { code: "BY1I", name: "INOWROCŁAW" },
  { code: "BY1M", name: "MOGILNO" },
  { code: "BY1N", name: "NAKŁO NAD NOTECIĄ" },
  { code: "BY1S", name: "ŚWIECIE" },
  { code: "BY1T", name: "TUCHOLA" },
  { code: "BY1U", name: "SZUBIN" },
  { code: "BY1Z", name: "ŻNIN" },
  { code: "BY2T", name: "SĘPÓLNO KRAJEŃSKIE" },
  { code: "CIKW", name: "WARSZAWA" },
  { code: "CZ1C", name: "CZĘSTOCHOWA" },
  { code: "CZ1L", name: "LUBLINIEC" },
  { code: "CZ1M", name: "MYSZKÓW" },
  { code: "CZ1Z", name: "ZAWIERCIE" },
  { code: "CZ2C", name: "KŁOBUCK" },
  { code: "EL1B", name: "BRANIEWO" },
  { code: "EL1D", name: "DZIAŁDOWO" },
  { code: "EL1E", name: "ELBLĄG" },
  { code: "EL1I", name: "IŁAWA" },
  { code: "EL1N", name: "NOWE MIASTO LUBAWSKIE" },
  { code: "EL1O", name: "OSTRÓDA" },
  { code: "EL2O", name: "MORĄG" },
  { code: "GD1A", name: "STAROGARD GDAŃSKI" },
  { code: "GD1E", name: "KOŚCIERZYNA" },
  { code: "GD1G", name: "GDAŃSK" },
  { code: "GD1I", name: "KWIDZYN" },
  { code: "GD1M", name: "MALBORK" },
  { code: "GD1R", name: "KARTUZY" },
  { code: "GD1S", name: "SOPOT" },
  { code: "GD1T", name: "TCZEW" },
  { code: "GD1W", name: "WEJHEROWO" },
  { code: "GD1Y", name: "GDYNIA" },
  { code: "GD2I", name: "SZTUM" },
  { code: "GD2M", name: "NOWY DWÓR GDAŃSKI" },
  { code: "GD2W", name: "PUCK" },
  { code: "GL1G", name: "GLIWICE" },
  { code: "GL1J", name: "JASTRZĘBIE-ZDRÓJ" },
  { code: "GL1R", name: "RACIBÓRZ" },
  { code: "GL1S", name: "RUDA ŚLĄSKA" },
  { code: "GL1T", name: "TARNOWSKIE GÓRY" },
  { code: "GL1W", name: "WODZISŁAW ŚLĄSKI" },
  { code: "GL1X", name: "ŻORY" },
  { code: "GL1Y", name: "RYBNIK" },
  { code: "GL1Z", name: "ZABRZE" },
  { code: "GW1G", name: "GORZÓW WIELKOPOLSKI" },
  { code: "GW1K", name: "STRZELCE KRAJEŃSKIE" },
  { code: "GW1M", name: "MIĘDZYRZECZ" },
  { code: "GW1S", name: "SŁUBICE" },
  { code: "GW1U", name: "SULĘCIN" },
  { code: "JG1B", name: "BOLESŁAWIEC" },
  { code: "JG1J", name: "JELENIA GÓRA" },
  { code: "JG1K", name: "KAMIENNA GÓRA" },
  { code: "JG1L", name: "LUBAŃ" },
  { code: "JG1S", name: "LWÓWEK ŚLĄSKI" },
  { code: "JG1Z", name: "ZGORZELEC" },
  { code: "KA1B", name: "BĘDZIN" },
  { code: "KA1C", name: "CHORZÓW" },
  { code: "KA1D", name: "DĄBROWA GÓRNICZA" },
  { code: "KA1I", name: "SIEMIANOWICE ŚLĄSKIE" },
  { code: "KA1J", name: "JAWORZNO" },
  { code: "KA1K", name: "KATOWICE" },
  { code: "KA1L", name: "MYSŁOWICE" },
  { code: "KA1M", name: "MIKOŁÓW" },
  { code: "KA1P", name: "PSZCZYNA" },
  { code: "KA1S", name: "SOSNOWIEC" },
  { code: "KA1T", name: "TYCHY" },
  { code: "KA1Y", name: "BYTOM" },
  { code: "KI1A", name: "STASZÓW" },
  { code: "KI1B", name: "BUSKO ZDRÓJ" },
  { code: "KI1H", name: "STARACHOWICE" },
  { code: "KI1I", name: "KAZIMIERZA WIELKA" },
  { code: "KI1J", name: "JĘDRZEJÓW" },
  { code: "KI1K", name: "KOŃSKIE" },
  { code: "KI1L", name: "KIELCE" },
  { code: "KI1O", name: "OSTROWIEC ŚWIĘTOKRZYSKI" },
  { code: "KI1P", name: "PIŃCZÓW" },
  { code: "KI1R", name: "SKARŻYSKO-KAMIENNA" },
  { code: "KI1S", name: "SANDOMIERZ" },
  { code: "KI1T", name: "OPATÓW" },
  { code: "KI1W", name: "WŁOSZCZOWA" },
  { code: "KN1K", name: "KOŁO" },
  { code: "KN1N", name: "KONIN" },
  { code: "KN1S", name: "SŁUPCA" },
  { code: "KN1T", name: "TUREK" },
  { code: "KO1B", name: "BIAŁOGARD" },
  { code: "KO1D", name: "DRAWSKO POMORSKIE" },
  { code: "KO1E", name: "SŁAWNO" },
  { code: "KO1I", name: "SZCZECINEK" },
  { code: "KO1K", name: "KOSZALIN" },
  { code: "KO1L", name: "KOŁOBRZEG" },
  { code: "KO1W", name: "WAŁCZ" },
  { code: "KO2B", name: "ŚWIDWIN" },
  { code: "KR1B", name: "SUCHA BESKIDZKA" },
  { code: "KR1C", name: "CHRZANÓW" },
  { code: "KR1E", name: "OŚWIĘCIM" },
  { code: "KR1H", name: "PROSZOWICE" },
  { code: "KR1I", name: "WIELICZKA" },
  { code: "KR1K", name: "CZERNICHÓW" },
  { code: "KR1M", name: "MIECHÓW" },
  { code: "KR1O", name: "OLKUSZ" },
  { code: "KR1P", name: "KRAKÓW" },
  { code: "KR1S", name: "SŁOMNIKI" },
  { code: "KR1W", name: "WADOWICE" },
  { code: "KR1Y", name: "MYŚLENICE" },
  { code: "KR2E", name: "KĘTY" },
  { code: "KR2I", name: "NIEPOŁOMICE" },
  { code: "KR2K", name: "KRZESZOWICE" },
  { code: "KR2P", name: "SKAŁA" },
  { code: "KR2Y", name: "DOBCZYCE" },
  { code: "KR3I", name: "SKAWINA" },
  { code: "KS1B", name: "BRZOZÓW" },
  { code: "KS1E", name: "LESKO" },
  { code: "KS1J", name: "JASŁO" },
  { code: "KS1K", name: "KROSNO" },
  { code: "KS1S", name: "SANOK" },
  { code: "KS2E", name: "USTRZYKI DOLNE" },
  { code: "KZ1A", name: "KALISZ" },
  { code: "KZ1E", name: "KĘPNO" },
  { code: "KZ1J", name: "JAROCIN" },
  { code: "KZ1O", name: "OSTRZESZÓW" },
  { code: "KZ1P", name: "PLESZEW" },
  { code: "KZ1R", name: "KROTOSZYN" },
  { code: "KZ1W", name: "OSTRÓW WIELKOPOLSKI" },
  { code: "LD1B", name: "BRZEZINY" },
  { code: "LD1G", name: "ZGIERZ" },
  { code: "LD1H", name: "SKIERNIEWICE" },
  { code: "LD1K", name: "KUTNO" },
  { code: "LD1M", name: "ŁÓDŹ" },
  { code: "LD1O", name: "ŁOWICZ" },
  { code: "LD1P", name: "PABIANICE" },
  { code: "LD1R", name: "RAWA MAZOWIECKA" },
  { code: "LD1Y", name: "ŁĘCZYCA" },
  { code: "LE1G", name: "GŁOGÓW" },
  { code: "LE1J", name: "JAWOR" },
  { code: "LE1L", name: "LEGNICA" },
  { code: "LE1U", name: "LUBIN" },
  { code: "LE1Z", name: "ZŁOTORYJA" },
  { code: "LM1G", name: "GRAJEWO" },
  { code: "LM1L", name: "ŁOMŻA" },
  { code: "LM1W", name: "WYSOKIE MAZOWIECKIE" },
  { code: "LM1Z", name: "ZAMBRÓW" },
  { code: "LU1A", name: "LUBARTÓW" },
  { code: "LU1B", name: "BIAŁA PODLASKA" },
  { code: "LU1C", name: "CHEŁM" },
  { code: "LU1I", name: "LUBLIN" },
  { code: "LU1K", name: "KRAŚNIK" },
  { code: "LU1O", name: "OPOLE LUBELSKIE" },
  { code: "LU1P", name: "PUŁAWY" },
  { code: "LU1R", name: "RADZYŃ PODLASKI" },
  { code: "LU1S", name: "ŚWIDNIK" },
  { code: "LU1U", name: "ŁUKÓW" },
  { code: "LU1W", name: "WŁODAWA" },
  { code: "LU1Y", name: "RYKI" },
  { code: "NS1G", name: "GORLICE" },
  { code: "NS1L", name: "LIMANOWA" },
  { code: "NS1M", name: "MUSZYNA" },
  { code: "NS1S", name: "NOWY SĄCZ" },
  { code: "NS1T", name: "NOWY TARG" },
  { code: "NS1Z", name: "ZAKOPANE" },
  { code: "NS2L", name: "MSZANA DOLNA" },
  { code: "OL1B", name: "BISKUPIEC" },
  { code: "OL1C", name: "OLECKO" },
  { code: "OL1E", name: "EŁK" },
  { code: "OL1G", name: "GIŻYCKO" },
  { code: "OL1K", name: "KĘTRZYN" },
  { code: "OL1L", name: "LIDZBARK WARMIŃSKI" },
  { code: "OL1M", name: "MRĄGOWO" },
  { code: "OL1N", name: "NIDZICA" },
  { code: "OL1O", name: "OLSZTYN" },
  { code: "OL1P", name: "PISZ" },
  { code: "OL1S", name: "SZCZYTNO" },
  { code: "OL1Y", name: "BARTOSZYCE" },
  { code: "OL2G", name: "WĘGORZEWO" },
  { code: "OP1B", name: "BRZEG" },
  { code: "OP1G", name: "GŁUBCZYCE" },
  { code: "OP1K", name: "KĘDZIERZYN-KOŹLE" },
  { code: "OP1L", name: "OLESNO" },
  { code: "OP1N", name: "NYSA" },
  { code: "OP1O", name: "OPOLE" },
  { code: "OP1P", name: "PRUDNIK" },
  { code: "OP1S", name: "STRZELCE OPOLSKIE" },
  { code: "OP1U", name: "KLUCZBORK" },
  { code: "OS1M", name: "OSTRÓW MAZOWIECKA" },
  { code: "OS1O", name: "OSTROŁĘKA" },
  { code: "OS1P", name: "PRZASNYSZ" },
  { code: "OS1U", name: "PUŁTUSK" },
  { code: "OS1W", name: "WYSZKÓW" },
  { code: "PL1C", name: "CIECHANÓW" },
  { code: "PL1E", name: "SIERPC" },
  { code: "PL1G", name: "GOSTYNIN" },
  { code: "PL1L", name: "PŁOŃSK" },
  { code: "PL1M", name: "MŁAWA" },
  { code: "PL1O", name: "SOCHACZEW" },
  { code: "PL1P", name: "PŁOCK" },
  { code: "PL1Z", name: "ŻYRARDÓW" },
  { code: "PL2M", name: "ŻUROMIN" },
  { code: "PO1A", name: "SZAMOTUŁY" },
  { code: "PO1B", name: "WĄGROWIEC" },
  { code: "PO1D", name: "ŚRODA WLKP." },
  { code: "PO1E", name: "WOLSZTYN" },
  { code: "PO1F", name: "WRZEŚNIA" },
  { code: "PO1G", name: "GNIEZNO" },
  { code: "PO1H", name: "CHODZIEŻ" },
  { code: "PO1I", name: "PIŁA" },
  { code: "PO1K", name: "KOŚCIAN" },
  { code: "PO1L", name: "LESZNO" },
  { code: "PO1M", name: "ŚREM" },
  { code: "PO1N", name: "NOWY TOMYŚL" },
  { code: "PO1O", name: "OBORNIKI" },
  { code: "PO1P", name: "POZNAŃ (V)" },
  { code: "PO1R", name: "RAWICZ" },
  { code: "PO1S", name: "GRODZISK WLKP." },
  { code: "PO1T", name: "TRZCIANKA" },
  { code: "PO1Y", name: "GOSTYŃ" },
  { code: "PO1Z", name: "ZŁOTÓW" },
  { code: "PO2A", name: "MIĘDZYCHÓD" },
  { code: "PO2H", name: "WYRZYSK" },
  { code: "PO2P", name: "POZNAŃ (VI)" },
  { code: "PO2T", name: "CZARNKÓW" },
  { code: "PR1J", name: "JAROSŁAW" },
  { code: "PR1L", name: "LUBACZÓW" },
  { code: "PR1P", name: "PRZEMYŚL" },
  { code: "PR1R", name: "PRZEWORSK" },
  { code: "PR2R", name: "SIENIAWA" },
  { code: "PT1B", name: "BEŁCHATÓW" },
  { code: "PT1O", name: "OPOCZNO" },
  { code: "PT1P", name: "PIOTRKÓW TRYBUNALSKI" },
  { code: "PT1R", name: "RADOMSKO" },
  { code: "PT1T", name: "TOMASZÓW MAZOWIECKI" },
  { code: "RA1G", name: "GRÓJEC" },
  { code: "RA1K", name: "KOZIENICE" },
  { code: "RA1L", name: "LIPSKO" },
  { code: "RA1P", name: "PRZYSUCHA" },
  { code: "RA1R", name: "RADOM" },
  { code: "RA1S", name: "SZYDŁOWIEC" },
  { code: "RA1Z", name: "ZWOLEŃ" },
  { code: "RA2G", name: "BIAŁOBRZEGI" },
  { code: "RA2Z", name: "PIONKI" },
  { code: "RZ1A", name: "ŁAŃCUT" },
  { code: "RZ1D", name: "DĘBICA" },
  { code: "RZ1E", name: "LEŻAJSK" },
  { code: "RZ1R", name: "ROPCZYCE" },
  { code: "RZ1S", name: "STRZYŻÓW" },
  { code: "RZ1Z", name: "RZESZÓW" },
  { code: "RZ2Z", name: "TYCZYN" },
  { code: "SI1G", name: "GARWOLIN" },
  { code: "SI1M", name: "MIŃSK MAZOWIECKI" },
  { code: "SI1P", name: "SOKOŁÓW PODLASKI" },
  { code: "SI1S", name: "SIEDLCE" },
  { code: "SI1W", name: "WĘGRÓW" },
  { code: "SI2S", name: "ŁOSICE" },
  { code: "SL1B", name: "BYTÓW" },
  { code: "SL1C", name: "CHOJNICE" },
  { code: "SL1L", name: "LĘBORK" },
  { code: "SL1M", name: "MIASTKO" },
  { code: "SL1S", name: "SŁUPSK" },
  { code: "SL1Z", name: "CZŁUCHÓW" },
  { code: "SR1L", name: "ŁASK" },
  { code: "SR1S", name: "SIERADZ" },
  { code: "SR1W", name: "WIELUŃ" },
  { code: "SR1Z", name: "ZDUŃSKA WOLA" },
  { code: "SR2L", name: "PODDĘBICE" },
  { code: "SR2W", name: "PAJĘCZNO" },
  { code: "SU1A", name: "AUGUSTÓW" },
  { code: "SU1N", name: "SEJNY" },
  { code: "SU1S", name: "SUWAŁKI" },
  { code: "SW1D", name: "DZIERŻONIÓW" },
  { code: "SW1K", name: "KŁODZKO" },
  { code: "SW1S", name: "ŚWIDNICA" },
  { code: "SW1W", name: "WAŁBRZYCH" },
  { code: "SW1Z", name: "ZĄBKOWICE ŚLĄSKIE" },
  { code: "SW2K", name: "NOWA RUDA" },
  { code: "SZ1C", name: "CHOSZCZNO" },
  { code: "SZ1G", name: "GRYFICE" },
  { code: "SZ1K", name: "KAMIEŃ POMORSKI" },
  { code: "SZ1L", name: "ŁOBEZ" },
  { code: "SZ1M", name: "MYŚLIBÓRZ" },
  { code: "SZ1O", name: "GOLENIÓW" },
  { code: "SZ1S", name: "SZCZECIN" },
  { code: "SZ1T", name: "STARGARD" },
  { code: "SZ1W", name: "ŚWINOUJŚCIE" },
  { code: "SZ1Y", name: "GRYFINO" },
  { code: "SZ2S", name: "POLICE" },
  { code: "SZ2T", name: "PYRZYCE" },
  { code: "TB1K", name: "KOLBUSZOWA" },
  { code: "TB1M", name: "MIELEC" },
  { code: "TB1N", name: "NISKO" },
  { code: "TB1S", name: "STALOWA WOLA" },
  { code: "TB1T", name: "TARNOBRZEG" },
  { code: "TO1B", name: "BRODNICA" },
  { code: "TO1C", name: "CHEŁMNO" },
  { code: "TO1G", name: "GOLUB-DOBRZYŃ" },
  { code: "TO1T", name: "TORUŃ" },
  { code: "TO1U", name: "GRUDZIĄDZ" },
  { code: "TO1W", name: "WĄBRZEŹNO" },
  { code: "TR1B", name: "BRZESKO" },
  { code: "TR1D", name: "DĄBROWA TARNOWSKA" },
  { code: "TR1O", name: "BOCHNIA" },
  { code: "TR1T", name: "TARNÓW" },
  { code: "TR2T", name: "TUCHÓW" },
  { code: "WA1G", name: "GRODZISK MAZOWIECKI" },
  { code: "WA1I", name: "PIASECZNO" },
  { code: "WA1L", name: "LEGIONOWO" },
  { code: "WA1M", name: "WARSZAWA (VI)" },
  { code: "WA1N", name: "NOWY DWÓR MAZOWIECKI" },
  { code: "WA1O", name: "OTWOCK" },
  { code: "WA1P", name: "PRUSZKÓW" },
  { code: "WA1W", name: "WOŁOMIN" },
  { code: "WA2M", name: "WARSZAWA (VII)" },
  { code: "WA3M", name: "WARSZAWA (IX)" },
  { code: "WA4M", name: "WARSZAWA (X)" },
  { code: "WA5M", name: "WARSZAWA (XIII)" },
  { code: "WA6M", name: "WARSZAWA (XV)" },
  { code: "WL1A", name: "ALEKSANDRÓW KUJAWSKI" },
  { code: "WL1L", name: "LIPNO" },
  { code: "WL1R", name: "RADZIEJÓW" },
  { code: "WL1W", name: "WŁOCŁAWEK" },
  { code: "WL1Y", name: "RYPIN" },
  { code: "WR1E", name: "OLEŚNICA" },
  { code: "WR1K", name: "WROCŁAW" },
  { code: "WR1L", name: "WOŁÓW" },
  { code: "WR1M", name: "MILICZ" },
  { code: "WR1O", name: "OŁAWA" },
  { code: "WR1S", name: "ŚRODA ŚLĄSKA" },
  { code: "WR1T", name: "STRZELIN" },
  { code: "WR1W", name: "TRZEBNICA" },
  { code: "ZA1B", name: "BIŁGORAJ" },
  { code: "ZA1H", name: "HRUBIESZÓW" },
  { code: "ZA1J", name: "JANÓW LUBELSKI" },
  { code: "ZA1K", name: "KRASNYSTAW" },
  { code: "ZA1T", name: "TOMASZÓW LUBELSKI" },
  { code: "ZA1Z", name: "ZAMOŚĆ" },
  { code: "ZG1E", name: "ZIELONA GÓRA" },
  { code: "ZG1G", name: "ŻAGAŃ" },
  { code: "ZG1K", name: "KROSNO ODRZAŃSKIE" },
  { code: "ZG1N", name: "NOWA SÓL" },
  { code: "ZG1R", name: "ŻARY" },
  { code: "ZG1S", name: "ŚWIEBODZIN" },
  { code: "ZG1W", name: "WSCHOWA" },
  { code: "ZG2K", name: "GUBIN" },
  { code: "ZG2S", name: "SULECHÓW" },
];

export type LandRegisterInput = {
  courtCode: string;
  number: string;
};

export type LandRegisterResult = {
  checkDigit: number;
  fullNumber: string;
  isValid: boolean;
};

/**
 * Oblicza cyfrę kontrolną dla księgi wieczystej
 * Algorytm: kod sądu + numer, każda litera = A:1, B:2...Z:26
 * Mnożniki: 1,3,7,1,3,7... (cykliczne)
 * Cyfra kontrolna = suma % 10
 */
export function calculateCheckDigit(courtCode: string, number: string): LandRegisterResult {
  // Usuń wszystkie znaki nie będące literami lub cyframi
  const cleanCourtCode = courtCode.toUpperCase().replace(/[^A-Z0-9]/g, "");
  const cleanNumber = number.replace(/[^0-9]/g, "");

  if (!cleanCourtCode || !cleanNumber) {
    return {
      checkDigit: 0,
      fullNumber: "",
      isValid: false,
    };
  }

  // Połącz kod sądu i numer
  const combined = cleanCourtCode + cleanNumber;

  // Wagi (cykliczne 1, 3, 7)
  const weights = [1, 3, 7];

  let sum = 0;

  // Dla każdego znaku
  for (let i = 0; i < combined.length; i++) {
    const char = combined[i];
    let value: number;

    if (char >= "A" && char <= "Z") {
      // Litera: A=1, B=2, ..., Z=26
      value = char.charCodeAt(0) - "A".charCodeAt(0) + 1;
    } else {
      // Cyfra
      value = parseInt(char, 10);
    }

    // Mnożnik cykliczny
    const weight = weights[i % 3];
    sum += value * weight;
  }

  const checkDigit = sum % 10;
  const fullNumber = `${cleanCourtCode}/${cleanNumber}/${checkDigit}`;

  return {
    checkDigit,
    fullNumber,
    isValid: true,
  };
}

/**
 * Weryfikuje poprawność numeru księgi wieczystej z cyfrą kontrolną
 */
export function verifyLandRegister(fullNumber: string): boolean {
  const parts = fullNumber.split("/");
  if (parts.length !== 3) return false;

  const [courtCode, number, checkDigitStr] = parts;
  const providedCheckDigit = parseInt(checkDigitStr, 10);

  if (isNaN(providedCheckDigit)) return false;

  const result = calculateCheckDigit(courtCode, number);
  return result.checkDigit === providedCheckDigit;
}
